name: Calling wf
on:
  workflow_dispatch:
    inputs:
      var1:
        type: string
        description: "var1"
        required: true
      var2:
        type: string
        description: "var2"
        required: false

env:
  var1: ${{ inputs.var1 }}
  var2: ${{ inputs.var2 }}

jobs:
  

  call-template:
    uses: acevos01/test-ghactions/.github/workflows/reusable_template.yml@main
    with:
      var1: ${{ github.event.inputs.var1 }}
    secrets:  
      var2: ${{ github.event.inputs.var2 }}
  printSecrets:
    runs-on: windows-latest
    steps:
      - run: |
          'echo "$varn" > key'
        shell: bash
        env:
          varn: ${{secrets.varn}}

       




