name: Testing
on:
  workflow_dispatch:
    inputs:
      # var1:
      #   type: string
      #   description: "var1"
      #   required: true
      # var2:
      #   type: string
      #   description: "var2"
      #   required: false
      Env:
        type: choice
        description: "Environment"
        options: 
        - RIS-XBVB7TQNFUJ
        - Windows10
        required: true
  repository_dispatch:
    types: [web]

env:
  # var1: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.var1 || github.event.client_payload.var1 }}
  pc: ""
jobs:
  dumpVars:
    runs-on: 
      - self-hosted
      - windows
      - x64
      - RIS-XBVB7TQNFUJ
      # - ${{ github.event.inputs.Env }}
    outputs:
      runner: ${{ steps.get-runner.outputs.runner }}
      
    steps:
      - name: PrintVars
        id: get-runner
        run: |
          Write-Output "pc=$(hostname)" >> $env:GITHUB_ENV
          Write-Output "Output Var1: ${{ env.var1 }} Event: ${{github.event_name}}"
          echo "::set-output name=runner::$(hostname)"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute script in time
        timeout-minutes: 1080
        run: | 
          .\mytestscript.ps1
        
  # download-file-github:
  #   needs: dumpVars
  #   runs-on: 
  #     - self-hosted
  #     - windows
  #     - x64
  #     - ${{ needs.dumpVars.outputs.runner }}
  #   steps:
  #     - run: |
  #           Invoke-WebRequest -Uri https://github.com/psf/black/archive/refs/heads/main.zip -OutFile psf-black.zip

  # another-job-using-output:
  #   runs-on: 
  #     - self-hosted
  #     - windows
  #     - x64
  #     - ${{ github.event.inputs.Env }}
  #   steps:
  #     - run: |
  #           Invoke-WebRequest -Uri https://github.com/psf/black/archive/refs/heads/main.zip -OutFile psf-black.zip
                          

    





