name: on-demand-test
on:
  repository_dispatch:
    types: [on-demand-test]
     
jobs:
  printSecrets:
    runs-on: windows-latest
    steps:
      - run: |
          echo ${{ github.event.client_payload.data }}
          echo ${{ github.event.client_payload.data.var2 }}

       




